### ISSUE TITLE
Pon los ejemplos en un programa aparte

### ISSUE THREAD

**Issue by JJ** [manuelalonsobraojos/cc-ejercicios#3]
Y en los ejercicios, el resultado de ejecutarlos, si es posible.

**Comment by lenum9** [comment]
https://github.com/manuelalonsobraojos/cc-ejercicios/blob/master/Ejercicios-tema4/EjerciciosTema4.md
Los ejercicios con enlaces a los códigos e imágenes de los resultados y ejecuciones realizadas
